services:
  app:
    build:
      context: .
    image: ${APP_NAME}
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      #- /app/node_modules
    command: >
      bash -c "npm install && npm run develop"
    ports:
      - ${PORT}:${PORT}
    networks:
      - appnetwork
    depends_on:
      - db
    working_dir: /app

  db:
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    env_file: .env
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - appnetwork

volumes:
  postgres-data:


networks:
  appnetwork:
    name: ${APP_NETWORK_NAME}
    driver: bridge
