name: Deploy to Production Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set image name and tag
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "TAG=main" >> $GITHUB_ENV

      - name: Choose GHCR login user
        run: |
          if [ -n "${{ secrets.GHCR_USERNAME }}" ]; then
            echo "GHCR_LOGIN=${{ secrets.GHCR_USERNAME }}" >> $GITHUB_ENV
          else
            echo "GHCR_LOGIN=${{ github.actor }}" >> $GITHUB_ENV
          fi

      - name: Log in to GHCR (for push)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -f Dockerfile.prod -t $IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$TAG

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PROD }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.SSH_HOST_PROD }} >> ~/.ssh/known_hosts

      - name: Deploy on Production Server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ vars.SSH_USER_PROD }}@${{ vars.SSH_HOST_PROD }} << EOF
            cd ${{ vars.DEPLOY_PATH_PROD }}
            git fetch --all
            git checkout main
            git reset --hard origin/main
          
            # Логин в GHCR
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
          
            # Обновляем .env
            sed -i '/^GITHUB_REPOSITORY=/d' .env || true
            sed -i '/^IMAGE_NAME=/d' .env || true
            sed -i '/^TAG=/d' .env || true
            echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY,,}" >> .env
            echo "IMAGE_NAME=$IMAGE_NAME" >> .env
            echo "TAG=$TAG" >> .env
            docker compose -f docker-compose.prod.yml down
            docker pull $IMAGE_NAME:$TAG
            docker compose -f docker-compose.prod.yml up -d
          EOF
